In [2]:
l = [23234, 37, 27, 215, -1234]

In [3]:
l

[23234, 37, 27, 215, -1234]

In [4]:
import numpy as np

In [6]:
a = np.array(l)

In [7]:
a

array([23234,    37,    27,   215, -1234])

In [8]:
b = np.array([12, 455, 63.4, True, "abc"])

In [9]:
b

array(['12', '455', '63.4', 'True', 'abc'], dtype='<U32')

In [11]:
print(b)  # Array has only one data type

['12' '455' '63.4' 'True' 'abc']


In [12]:
l.pop

<function list.pop(index=-1, /)>

In [15]:
l.pop()

215

In [16]:
l

[23234, 37, 27]

In [17]:
a.mean()

4455.8

In [18]:
#------ array slicing

In [19]:
a[2:]

array([   27,   215, -1234])

In [20]:
a[2:4]

array([ 27, 215])

In [21]:
b =a[2:4]

In [22]:
b

array([ 27, 215])

In [23]:
b[0]

27

In [24]:
b[:] = 111  #-- value of all elements changes

In [25]:
b

array([111, 111])

In [26]:
a

array([23234,    37,   111,   111, -1234])

In [27]:
c = a.copy()  #-- makes a copy and does not change the original value

In [28]:
c

array([23234,    37,   111,   111, -1234])

In [29]:
c[0] = 0

In [30]:
c

array([    0,    37,   111,   111, -1234])

In [31]:
a

array([23234,    37,   111,   111, -1234])